[programs.localnet]
gem_bank = "BANKYwnXt78xLEEUeKnAZTa3wLHQkrgVJd28j5APxx91"
gem_farm = "FARMQDpJuUquVynDzyWiPgniR35Vw5bd79xZ3McmEbb5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://billowing-floral-morning.solana-mainnet.quiknode.pro/5fa39a46e288be6db22973a1806d0f11e2d03a79/"
wallet = "/home/snghbeer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"